language: csharp

solution: gossiperl-client-dotnet.sln

sudo: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install wget curl jq
  - wget https://s3-eu-west-1.amazonaws.com/gossiperl-cdn/gossiperl-1.0.0_all.deb
  - sudo dpkg -i gossiperl-1.0.0_all.deb
  - sudo /etc/gossiperl/start-and-wait.sh
  - sudo /etc/gossiperl/test-overlay.sh

install:
  - sudo apt-get install -y mono-complete nunit
  - mozroots --import --sync
  - mkdir -p packages
  - wget https://nuget.org/nuget.exe
  - cp dll/Microsoft.Build.dll Microsoft.Build.dll
  - mono --runtime=v4.0 nuget.exe install exec/packages.config -OutputDirectory packages
  - mono --runtime=v4.0 nuget.exe install lib/packages.config -OutputDirectory packages
  - mono --runtime=v4.0 nuget.exe install tests/packages.config -OutputDirectory packages
  - xbuild gossiperl-client-dotnet.sln

script: nunit-console tests/gossiperl-client-tests.csproj

notifications:
  email: false